"""Page-break sentinel injection, applied outside protected table spans.

HTML carries page structure in four places: a CSS `page-break-*` / `break-*`
declaration on any element, an `<hr>`, a `<page>` tag (DSS-style output), and
a `class`/`id` hint token from a filing generator's own template vocabulary.
None of those survives plain-text projection as a page boundary, so this module
substitutes a sentinel that does.

**Break tags inside a table are page furniture, not page boundaries.** A
decorative `<hr>` used as a row rule, or an underlined column header, would be
converted to a sentinel, and the ASCII table renderer would then treat that
sentinel as cell text and wrap it at column widths — corrupting both the table
and the sentinel, so the later sentinel-to-marker pass could not recover it.
Every substitution therefore skips `<TABLE>` spans, using the byte-exact
protection contract from `edgar_sec.engine.tables.protection.tags`.
"""

from __future__ import annotations

import re

from edgar_sec.engine.document.html.normalizer import (
    NormalizedHtmlText,
    normalize_html_document,
)
from edgar_sec.engine.tables.protection.tags import find_table_spans
from edgar_sec.foundation.regex.builder import build_alternation

_BREAK_PROPERTIES = build_alternation(
    ["page-break-before", "page-break-after", "break-before", "break-after"],
    auto_escape=True,
)
_BREAK_VALUES = build_alternation(
    ["always", "page", "all", "left", "right", "recto", "verso"],
    auto_escape=True,
)
_RE_CSS_PAGE_BREAKS = re.compile(
    rf"""<[^>]*style=[\"'][^\"']*(?:{_BREAK_PROPERTIES})\s*:\s*(?:{_BREAK_VALUES})\b[^\"']*[\"'][^>]*>""",
    re.IGNORECASE,
)
_RE_HR_TAGS = re.compile(r"<hr\b[^>]*>", re.IGNORECASE)
_RE_PAGE_TAGS = re.compile(r"</?page\b[^>]*>", re.IGNORECASE)

# Canonical break-role entries for page-hint tokens: class/id names
# generated by filing systems for a page boundary. Number-, header-,
# footer-, and container-role tokens belong to page analysis, not break substitution.
PAGE_BREAK_HINT_TOKENS: tuple[str, ...] = (
    "pagebreak",
    "ctpagebreak",
    "pgbrk",
    "pgbk",
    "pagebreakbefore",
    "pagebreakafter",
    "breakbefore",
    "breakafter",
    "dspfpagebreak",
    "dspfpagebreakarea",
    "lastpagebreak",
)
_BREAK_HINTS_ALT = build_alternation(PAGE_BREAK_HINT_TOKENS, auto_escape=True)
_RE_CLASS_ID_PAGE_BREAKS = re.compile(
    rf"""<[^>]+(?:class|id)=[\"'][^\"']*\b(?:{_BREAK_HINTS_ALT})\b[^\"']*[\"'][^>]*>""",
    re.IGNORECASE,
)

_RE_PAGE_SENTINEL_RUN = re.compile(r"(?:\n\s*<PAGE>\s*)+")

# "SPLIT" deliberately avoids the letters r/R: the Stage-1 glyph pass maps r/R
# to checkbox glyphs inside Wingdings/Webdings/Symbol font scopes, which would
# corrupt the sentinel into e.g. "__SEC_PAGE_B[ ]EAK_SENTINEL__".
PAGE_SPLIT_SENTINEL = "__SEC_PAGE_SPLIT_SENTINEL__"

# The canonical marker this sentinel becomes in the ASCII text frame. It is an
# internal transport form: page-artifact rendering emits `[[SEC:PAGE_BREAK
# id=N]]` at the artifact boundary, and this module never emits that token.
PAGE_MARKER_LINE = "<PAGE>"

# One combined pattern. The rules share the sentinel replacement and are
# mutually exclusive tag prefixes, so this alternation reproduces the outcome
# of applying them sequentially.
_RE_BREAK_TAGS = re.compile(
    f"{_RE_PAGE_TAGS.pattern}|{_RE_HR_TAGS.pattern}"
    f"|{_RE_CSS_PAGE_BREAKS.pattern}|{_RE_CLASS_ID_PAGE_BREAKS.pattern}",
    re.IGNORECASE,
)


def insert_page_sentinels(html: str) -> str:
    """Replace page-break markup with the page-split sentinel, outside tables.

    Returns the input unchanged when it holds no `<TABLE>` span, and otherwise
    substitutes only in the gaps between spans.
    """
    replacement = f"\n{PAGE_SPLIT_SENTINEL}\n"
    spans = find_table_spans(html)
    if not spans:
        return _RE_BREAK_TAGS.sub(replacement, html)
    pieces: list[str] = []
    cursor = 0
    for span in spans:
        pieces.append(_RE_BREAK_TAGS.sub(replacement, html[cursor : span.start]))
        pieces.append(html[span.start : span.end])
        cursor = span.end
    pieces.append(_RE_BREAK_TAGS.sub(replacement, html[cursor:]))
    return "".join(pieces)


def collapse_marker_runs(text: str) -> str:
    """Collapse adjacent ``<PAGE>`` marker runs into one.

    Applied after the sentinel has become a marker, which is the only point at
    which markers exist: break markup is replaced with the sentinel *before*
    projection, so the marker form never appears in the text this pass receives.
    A repeated marker is preserved rather than merged — two breaks in a row are
    evidence of a blank page, and page analysis decides what that means.
    """
    return _RE_PAGE_SENTINEL_RUN.sub(f"\n{PAGE_MARKER_LINE}\n", text)


def render_html_to_break_text(html: str) -> NormalizedHtmlText:
    """Project HTML into the text frame, carrying page boundaries across.

    Break markup is replaced with the transport sentinel *before* the document
    is projected, because by projection time the tags are gone. The sentinel
    then becomes the canonical ``<PAGE>`` marker, adjacent markers are
    collapsed, and the table geometry the projection produced is carried
    through unchanged.

    The result is the frame page analysis reads. It is not yet the published
    text: page-marker policy in slice 4 decides what happens to each marker.
    """
    if not html:
        return NormalizedHtmlText("", ())
    normalized = normalize_html_document(insert_page_sentinels(html))
    converted = collapse_marker_runs(
        str(normalized).replace(PAGE_SPLIT_SENTINEL, f"\n{PAGE_MARKER_LINE}\n")
    )
    return NormalizedHtmlText(converted.strip(), normalized.table_geometries)


__all__ = [
    "PAGE_BREAK_HINT_TOKENS",
    "PAGE_MARKER_LINE",
    "PAGE_SPLIT_SENTINEL",
    "collapse_marker_runs",
    "insert_page_sentinels",
    "render_html_to_break_text",
]
