"""Generic text and phrase normalization infrastructure."""

from __future__ import annotations

from .automaton import (
    ClassificationMatch,
    LexicalMatcher,
    MatchedTerm,
    MatchPayload,
    MultiPatternAutomaton,
    compile_family_automaton,
    compile_lexical_matcher,
)
from .bow import (
    BowScore,
    CaseMode,
    CompiledEvidencePack,
    EvidenceContext,
    EvidenceHit,
    EvidenceTier,
    LexicalEvidencePack,
    Token,
    compile_evidence_pack,
    normalize_tokens,
    score_tokens,
    score_unit,
    tokenize,
)
from .compounds import (
    expand_alternations,
    expand_compounds,
    expand_variants,
)
from .dates import (
    CENTURY_PIVOT,
    MONTH_ALIASES,
    MONTH_NAME_RE,
    MONTH_NAMES,
    MONTH_PATTERN,
    MONTH_RE,
    MONTH_SUFFIX_RE,
    ORDINAL_SUFFIX_PATTERN,
    ORDINAL_SUFFIX_RE,
    SEC_DATE_FORMATS,
    TABLE_YEAR_RE,
    YEAR_IN_TEXT_RE,
    YEAR_RANGE,
    YEAR_TOKEN_RE,
    DateComponents,
    DateFormat,
    ParsedDate,
    extract_years,
    heal_date_fragments,
    month_name_to_index,
    parse_date,
    parse_numeric_year,
    parse_year_token,
)
from .healing import (
    CANONICAL_CHECKED,
    CANONICAL_UNCHECKED,
    NEGATIVE_BOUNDARY_RE,
    RE_RAW_CHECKED,
    RE_RAW_UNCHECKED,
    PhraseSequenceRule,
    classify_mark_line,
    heal_split_lines,
    merge_yes_no_binary_blocks,
    normalize_checkbox_tokens,
    normalize_whitespace_and_tabs,
    should_join_two_lines,
    strip_alphanumeric_words,
    strip_boxdot_spacers,
)
from .html import (
    FastHtmlNode,
    FastHtmlTree,
    clean_html_for_parsing,
    decompose_html_structures,
    extract_ascii_pre,
    parse_html,
    strip_benign_font_styles,
    strip_font_tag_and_noise_attributes,
    strip_ixbrl_inline_tags,
    strip_office_metadata_attributes,
)
from .tokens import (
    BULLET_MARKER_RE,
    BULLET_MARKERS,
)
from .unicode import (
    NORMALIZE_TO_SPACE,
    STRIP_ZERO_WIDTH,
    sanitize_unicode_whitespace,
)
from .whitespace import normalize_final_text_whitespace

__all__ = [
    "ACTION_PRESERVE",
    "ACTION_TAG_AND_PRESERVE",
    "ACTION_UNWRAP",
    "BULLET_MARKERS",
    "BULLET_MARKER_RE",
    "CANONICAL_CHECKED",
    "CANONICAL_UNCHECKED",
    "CENTURY_PIVOT",
    "MONTH_ALIASES",
    "MONTH_NAMES",
    "MONTH_NAME_RE",
    "MONTH_PATTERN",
    "MONTH_RE",
    "MONTH_SUFFIX_RE",
    "NEGATIVE_BOUNDARY_RE",
    "NORMALIZE_TO_SPACE",
    "ORDINAL_SUFFIX_PATTERN",
    "ORDINAL_SUFFIX_RE",
    "RE_RAW_CHECKED",
    "RE_RAW_UNCHECKED",
    "SEC_DATE_FORMATS",
    "STRIP_ZERO_WIDTH",
    "TABLE_YEAR_RE",
    "YEAR_IN_TEXT_RE",
    "YEAR_RANGE",
    "YEAR_TOKEN_RE",
    "BowScore",
    "CaseMode",
    "ClassificationMatch",
    "CompiledEvidencePack",
    "DateComponents",
    "DateFormat",
    "EvidenceContext",
    "EvidenceHit",
    "EvidenceTier",
    "FastHtmlNode",
    "FastHtmlTree",
    "LexicalEvidencePack",
    "LexicalMatcher",
    "MatchPayload",
    "MatchedTerm",
    "MultiPatternAutomaton",
    "ParsedDate",
    "PhraseSequenceRule",
    "ReflowResult",
    "SpanDecision",
    "Token",
    "classify_mark_line",
    "clean_html_for_parsing",
    "compile_evidence_pack",
    "compile_family_automaton",
    "compile_lexical_matcher",
    "decompose_html_structures",
    "expand_alternations",
    "expand_compounds",
    "expand_variants",
    "extract_ascii_pre",
    "extract_years",
    "heal_date_fragments",
    "heal_split_lines",
    "merge_yes_no_binary_blocks",
    "month_name_to_index",
    "normalize_checkbox_tokens",
    "normalize_final_text_whitespace",
    "normalize_tokens",
    "normalize_whitespace_and_tabs",
    "parse_date",
    "parse_html",
    "parse_numeric_year",
    "parse_year_token",
    "reflow_ascii",
    "sanitize_unicode_whitespace",
    "score_tokens",
    "score_unit",
    "should_join_two_lines",
    "strip_alphanumeric_words",
    "strip_benign_font_styles",
    "strip_boxdot_spacers",
    "strip_font_tag_and_noise_attributes",
    "strip_ixbrl_inline_tags",
    "strip_office_metadata_attributes",
    "tokenize",
]


def __getattr__(name: str):
    """Load the table-dependent reflow API only when it is requested."""
    reflow_names = {
        "ACTION_PRESERVE",
        "ACTION_TAG_AND_PRESERVE",
        "ACTION_UNWRAP",
        "ReflowResult",
        "SpanDecision",
        "reflow_ascii",
    }
    if name in reflow_names:
        from . import reflow as _reflow

        value = getattr(_reflow, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
