"""Generic text and phrase normalization infrastructure."""

from __future__ import annotations

from .dates import (
    CENTURY_PIVOT,
    MONTH_ALIASES,
    MONTH_NAME_RE,
    MONTH_NAMES,
    MONTH_PATTERN,
    MONTH_RE,
    MONTH_SUFFIX_RE,
    ORDINAL_SUFFIX_PATTERN,
    ORDINAL_SUFFIX_RE,
    SEC_DATE_FORMATS,
    TABLE_YEAR_RE,
    YEAR_IN_TEXT_RE,
    YEAR_RANGE,
    YEAR_TOKEN_RE,
    DateComponents,
    DateFormat,
    ParsedDate,
    extract_years,
    heal_date_fragments,
    month_name_to_index,
    parse_date,
    parse_numeric_year,
    parse_year_token,
)
from .healing import (
    CANONICAL_CHECKED,
    CANONICAL_UNCHECKED,
    NEGATIVE_BOUNDARY_RE,
    RE_RAW_CHECKED,
    RE_RAW_UNCHECKED,
    PhraseSequenceRule,
    classify_mark_line,
    heal_split_lines,
    merge_yes_no_binary_blocks,
    normalize_checkbox_tokens,
    normalize_whitespace_and_tabs,
    should_join_two_lines,
    strip_alphanumeric_words,
    strip_boxdot_spacers,
)

__all__ = [
    "CANONICAL_CHECKED",
    "CANONICAL_UNCHECKED",
    "CENTURY_PIVOT",
    "MONTH_ALIASES",
    "MONTH_NAMES",
    "MONTH_NAME_RE",
    "MONTH_PATTERN",
    "MONTH_RE",
    "MONTH_SUFFIX_RE",
    "NEGATIVE_BOUNDARY_RE",
    "ORDINAL_SUFFIX_PATTERN",
    "ORDINAL_SUFFIX_RE",
    "RE_RAW_CHECKED",
    "RE_RAW_UNCHECKED",
    "SEC_DATE_FORMATS",
    "TABLE_YEAR_RE",
    "YEAR_IN_TEXT_RE",
    "YEAR_RANGE",
    "YEAR_TOKEN_RE",
    "DateComponents",
    "DateFormat",
    "ParsedDate",
    "PhraseSequenceRule",
    "classify_mark_line",
    "extract_years",
    "heal_date_fragments",
    "heal_split_lines",
    "merge_yes_no_binary_blocks",
    "month_name_to_index",
    "normalize_checkbox_tokens",
    "normalize_whitespace_and_tabs",
    "parse_date",
    "parse_numeric_year",
    "parse_year_token",
    "should_join_two_lines",
    "strip_alphanumeric_words",
    "strip_boxdot_spacers",
]
