"""Public page-marker API across ASCII and future representations."""

from .artifacts import (
    build_page_artifact_metadata,
    normalize_template_text,
    parse_page_artifact,
    parse_page_break_artifact,
    render_page_artifact,
    render_page_break_artifact,
    template_id_for,
    token_kind_for,
)
from .ascii import (
    RE_PAGE_SUFFIX,
    analyze_page_markers,
    analyze_repeating_headers,
    apply_page_markers,
    classify_candidate,
    extract_ascii_pre,
    find_page_markers,
    is_page_marker_line,
    roman_to_int,
    strip_page_markers,
)
from .html import (
    apply_html_page_decisions,
    apply_html_page_policy,
    enrich_html_analysis,
    refresh_html_analysis,
)
from .models import (
    InferredBoundary,
    PageArtifactPolicy,
    PageBreakArtifact,
    PageCandidate,
    PageMarker,
    PageMarkerAction,
    PageMarkerAnalysis,
    PageMarkerDecision,
    PageMarkerKind,
    PageMarkerSpan,
    PageMarkerTerminalState,
    PageNumberRun,
    PageRegionReport,
    TemplateEvidence,
)

__all__ = [
    "RE_PAGE_SUFFIX",
    "InferredBoundary",
    "PageArtifactPolicy",
    "PageBreakArtifact",
    "PageCandidate",
    "PageMarker",
    "PageMarkerAction",
    "PageMarkerAnalysis",
    "PageMarkerDecision",
    "PageMarkerKind",
    "PageMarkerSpan",
    "PageMarkerTerminalState",
    "PageNumberRun",
    "PageRegionReport",
    "TemplateEvidence",
    "analyze_page_markers",
    "analyze_repeating_headers",
    "apply_html_page_decisions",
    "apply_html_page_policy",
    "apply_page_markers",
    "build_page_artifact_metadata",
    "classify_candidate",
    "enrich_html_analysis",
    "extract_ascii_pre",
    "find_page_markers",
    "is_page_marker_line",
    "normalize_template_text",
    "parse_page_artifact",
    "parse_page_break_artifact",
    "refresh_html_analysis",
    "render_page_artifact",
    "render_page_break_artifact",
    "roman_to_int",
    "strip_page_markers",
    "template_id_for",
    "token_kind_for",
]
