"""Shared phase runtime contracts."""

from .artifacts import (
    artifact_id,
    create_bundle,
    find_manifests,
    import_bundle,
    load_manifest,
    make_manifest,
    manifest_relative_path,
    prepare_bundle_for_phase,
    publish_manifest,
    relative_path,
    resolve_dependencies,
    resolve_manifest,
    resolve_source,
    validate_manifest,
)
from .checks import Scanner, ScannerFinding, register, registered, run_all
from .cli import add_common_options, coalesce, load_config_or_template, print_json
from .env import (
    DEFAULT_DOTENV_PATH,
    get_env,
    load_dotenv,
    render_dotenv_value,
    scan_modified_environment_access,
)
from .interactive import InteractivePhase, run_interactive
from .partitions import divide_ids_among_workers, parse_id_selection
from .paths import (
    MERGE_DIR_NAME,
    MERGE_REPORT_NAME,
    ArtifactClassification,
    ArtifactRole,
    PhasePaths,
    ProjectPaths,
    RunPaths,
    classify_artifact_path,
    merge_report_path_in,
    partition_merge_report_path_in,
    partition_merge_root_in,
    resolve_paths,
)
from .progress import make_merge_progress_callback, make_tqdm_callback
from .registry import (
    ENTRIES,
    LauncherEntry,
    PhaseDependency,
    find_entry,
    get_phase_dependencies,
)
from .resources import (
    RuntimeResourceProfile,
    auto_worker_count,
    available_memory_bytes,
    derive_resources,
    usable_memory_bytes,
)
from .settings import (
    MISSING,
    SettingSpec,
    collect_specs,
    environment_name,
    flatten_settings,
    get_setting,
    render_dotenv,
    resolve_settings,
)
from .settings.runtime import (
    DEFAULT_CHUNK_SIZE,
    DEFAULT_PARTITION_COUNT,
)

__all__ = [
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_DOTENV_PATH",
    "DEFAULT_PARTITION_COUNT",
    "ENTRIES",
    "MERGE_DIR_NAME",
    "MERGE_REPORT_NAME",
    "MISSING",
    "ArtifactClassification",
    "ArtifactRole",
    "InteractivePhase",
    "LauncherEntry",
    "PhaseDependency",
    "PhasePaths",
    "ProjectPaths",
    "RunPaths",
    "RuntimeResourceProfile",
    "Scanner",
    "ScannerFinding",
    "SettingSpec",
    "add_common_options",
    "artifact_id",
    "auto_worker_count",
    "available_memory_bytes",
    "classify_artifact_path",
    "coalesce",
    "collect_specs",
    "create_bundle",
    "derive_resources",
    "divide_ids_among_workers",
    "environment_name",
    "find_entry",
    "find_manifests",
    "flatten_settings",
    "get_env",
    "get_phase_dependencies",
    "get_setting",
    "import_bundle",
    "load_config_or_template",
    "load_dotenv",
    "load_manifest",
    "make_manifest",
    "make_merge_progress_callback",
    "make_tqdm_callback",
    "manifest_relative_path",
    "merge_report_path_in",
    "parse_id_selection",
    "partition_merge_report_path_in",
    "partition_merge_root_in",
    "prepare_bundle_for_phase",
    "print_json",
    "publish_manifest",
    "register",
    "registered",
    "relative_path",
    "render_dotenv",
    "render_dotenv_value",
    "resolve_dependencies",
    "resolve_manifest",
    "resolve_paths",
    "resolve_settings",
    "resolve_source",
    "run_all",
    "run_interactive",
    "scan_modified_environment_access",
    "usable_memory_bytes",
    "validate_manifest",
]
