from edgar_sec.pipelines.document_inventory.schemas import (
    INVENTORY_ACCESSIONS_SCHEMA,
    INVENTORY_ACCESSIONS_SPEC,
    INVENTORY_ACCESSION_SOURCES_SCHEMA,
    INVENTORY_ACCESSION_SOURCES_SPEC,
    INVENTORY_ENTRIES_SCHEMA,
    INVENTORY_ENTRIES_SPEC,
    INVENTORY_RELATIONS,
)
from edgar_sec.pipelines.document_inventory.snapshot.schema import (
    SNAPSHOT_ACCESSION_SOURCES_SCHEMA,
    SNAPSHOT_ACCESSIONS_SCHEMA,
)
from edgar_sec.pipelines.document_inventory.snapshot.specs import (
    INVENTORY_ACCESSIONS_SPEC as SNAPSHOT_ACCESSIONS_SPEC,
    INVENTORY_ACCESSION_SOURCES_SPEC as SNAPSHOT_ACCESSION_SOURCES_SPEC,
    INVENTORY_ENTRIES_SPEC as SNAPSHOT_ENTRIES_SPEC,
    INVENTORY_RELATIONS as SNAPSHOT_RELATIONS,
)


def test_public_schema_contracts_are_owned_by_snapshot_modules() -> None:
    assert INVENTORY_ACCESSIONS_SCHEMA is SNAPSHOT_ACCESSIONS_SCHEMA
    assert INVENTORY_ACCESSION_SOURCES_SCHEMA is SNAPSHOT_ACCESSION_SOURCES_SCHEMA
    assert INVENTORY_ENTRIES_SCHEMA is SNAPSHOT_ENTRIES_SPEC.schema
    assert INVENTORY_ACCESSIONS_SPEC is SNAPSHOT_ACCESSIONS_SPEC
    assert INVENTORY_ACCESSION_SOURCES_SPEC is SNAPSHOT_ACCESSION_SOURCES_SPEC
    assert INVENTORY_ENTRIES_SPEC is SNAPSHOT_ENTRIES_SPEC
    assert INVENTORY_RELATIONS is SNAPSHOT_RELATIONS
