"""Public relation contracts for document inventory snapshots."""

from __future__ import annotations

from edgar_sec.pipelines.document_inventory.snapshot.schema import (
    LOOKUP_LAYOUT_VERSION,
    SNAPSHOT_ACCESSION_SOURCES_SCHEMA,
    SNAPSHOT_ACCESSIONS_SCHEMA,
    SNAPSHOT_RELATION_VERSION,
)
from edgar_sec.pipelines.document_inventory.snapshot.specs import (
    INVENTORY_ACCESSIONS_SPEC,
    INVENTORY_ACCESSION_SOURCES_SPEC,
    INVENTORY_ENTRIES_SPEC,
    INVENTORY_RELATIONS,
)

INVENTORY_ACCESSIONS_SCHEMA = INVENTORY_ACCESSIONS_SPEC.schema
INVENTORY_ACCESSION_SOURCES_SCHEMA = INVENTORY_ACCESSION_SOURCES_SPEC.schema
INVENTORY_ENTRIES_SCHEMA = INVENTORY_ENTRIES_SPEC.schema

__all__ = [
    "INVENTORY_ACCESSIONS_SCHEMA",
    "INVENTORY_ACCESSIONS_SPEC",
    "INVENTORY_ACCESSION_SOURCES_SCHEMA",
    "INVENTORY_ACCESSION_SOURCES_SPEC",
    "INVENTORY_ENTRIES_SCHEMA",
    "INVENTORY_ENTRIES_SPEC",
    "INVENTORY_RELATIONS",
    "LOOKUP_LAYOUT_VERSION",
    "SNAPSHOT_ACCESSION_SOURCES_SCHEMA",
    "SNAPSHOT_ACCESSIONS_SCHEMA",
    "SNAPSHOT_RELATION_VERSION",
]
