"""Distribution protocol, contracts, and transfer data models."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Protocol


@dataclass(frozen=True, slots=True)
class WorkerAssignment:
    """Assignment metadata for one worker bundle."""

    pipeline: str
    plan_id: str
    worker_id: str
    chunk_ids: tuple[int, ...]
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class WorkerReceipt:
    """Cryptographic proof of work generated by a completed worker."""

    pipeline: str
    plan_id: str
    worker_id: str
    completed_chunks: tuple[int, ...]
    row_count: int
    digests: dict[str, str]  # relative_chunk_path -> sha256


@dataclass(frozen=True, slots=True)
class ImportReport:
    """Outcome of coordinator chunk adoption."""

    pipeline: str
    plan_id: str
    worker_id: str
    adopted_chunks: tuple[int, ...]
    ignored_chunks: tuple[int, ...]


class DistributionAdapter(Protocol):
    """Pipeline-supplied hooks for distributed execution."""

    @property
    def pipeline_name(self) -> str:
        """Canonical short name of the pipeline (e.g. 'metadata', 'inventory')."""
        ...

    def resolve_plan(self, plan_id: str, artifacts_root: Path | None = None) -> Any:
        """Resolve and validate plan existence and total chunk count."""
        ...

    def get_chunk_count(self, plan: Any) -> int:
        """Return total number of work chunks in this plan."""
        ...

    def default_destination(self, plan_id: str) -> Path:
        """Default export destination path for this plan."""
        ...

    def export_worker_bundle(
        self,
        plan: Any,
        assignment: WorkerAssignment,
        bundle_dir: Path,
    ) -> None:
        """Copy required plan context (roster, work-order slice) into worker bundle."""
        ...

    def execute_worker(
        self,
        bundle_dir: Path,
        worker_id: str | None,
        *,
        workers: int | None = None,
    ) -> WorkerReceipt:
        """Execute assigned work chunks locally and return verified receipt."""
        ...

    def adopt_worker_bundle(
        self,
        plan: Any,
        bundle_dir: Path,
        receipt: WorkerReceipt,
    ) -> ImportReport:
        """Verify receipt against original plan and adopt chunks into coordinator tree."""
        ...
